app:
  environment: production
  port: 8005
  jwt-secret: leeycmintongg
  client-url: https://mintongg.netlify.app
db:
  username: postgres
  host: localhost
  port: 15432
  database: postgres
  password: mysecretpassword
  synchronize: false
