app:
  environment: production
  port: 3000
  jwt-secret: leeycmintongg
  client-url: https://mintongg.netlify.app
db:
  username: postgres
  host: postgresql
  port: 5432
  database: postgres
  password: mysecretpassword
  synchronize: false
